# Generated by Django 2.2 on 2020-07-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='options/%Y/%m/%d'),
        ),
    ]
