# Generated by Django 2.2 on 2020-05-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200528_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_accept',
            field=models.BooleanField(default=False),
        ),
    ]
