# Generated by Django 2.2 on 2020-07-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_can_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_create_vote',
            field=models.BooleanField(default=False),
        ),
    ]
