# Generated by Django 2.2 on 2020-05-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='idea',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
