# Generated by Django 2.2 on 2020-07-15 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_auto_20200604_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={},
        ),
    ]
